version: 0.2

env:
  variables:
    AWS_REGION:      "eu-west-2"
  parameter-store:
    ad_admin_username: "/$ENVIRONMENT_NAME/delius/mis-activedirectory/ad/ad_admin_username"
    ad_admin_password: "/$ENVIRONMENT_NAME/delius/mis-activedirectory/ad/ad_admin_password"
phases:
  build:
    commands:
      - ${CODEBUILD_SRC_DIR}/run.sh $ENVIRONMENT_NAME activedirectory apply
      - ${CODEBUILD_SRC_DIR}/run.sh $ENVIRONMENT_NAME fsx apply 
      